name: .NET Build

on:
  push:
  pull_request:

jobs:
  setup:
    name: Setup
    runs-on: self-hosted
    if: "!contains(toJSON(github.event.commits.*.message), '[ci-skip]')"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
  build:
    name: Build
    runs-on: self-hosted
    if: "!contains(toJSON(github.event.commits.*.message), '[ci-skip]')"
    uses: oolunar/dsharpplus.commandall/.github/workflows/dotnet_build.yml
    steps:
      - name: Build
        run: dotnet publish src/OoLunar.DSharpPlus.CommandAll.csproj -c Debug -f net7.0 --self-contained -p:DebugType=embedded
      - name: Upload Artifact
        uses: actions/upload-artifact@v2.2.4
        if: ${{ github.event_name == 'push' }}
        with:
          name: OoLunar.DSharpPlus.CommandAll-${{ GITHUB_RUN_NUMBER }}âˆ•${{ GITHUB_RUN_ATTEMPT }}
          path: ./src/bin/Debug/net7.0/publish/
  test:
    name: Test
    runs-on: self-hosted
    if: "!contains(toJSON(github.event.commits.*.message), '[ci-skip]')"
    uses: oolunar/dsharpplus.commandall/.github/workflows/dotnet_build.yml
    steps:
      - name: Test
        run: dotnet test --blame --blame-hang-timeout=30s